loaders:
  - modules:
      - haystack_integrations.components.websearch.exa.exa_websearch
    search_path: [../src]
processors:
  - type: filter
    documented_only: true
    skip_empty_modules: true
renderer:
  description: Exa integration for Haystack
  id: integrations-exa
  filename: exa.md
  title: Exa
